# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSApp

  flutter_application_path = '../flutterModule'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

install_all_flutter_pods(flutter_application_path)

  target 'iOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSAppUITests' do
    # Pods for testing
  end

end
